# docker-compose.yml
version: '3.8'

services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    ports:
      - "9123:8080"
    volumes:
      # Docker follows this symlink to store data in /opt/docker-data/searxng
      - ./searxng-data:/etc/searxng:rw
    environment:
      - SEARXNG_API_KEY=${SEARXNG_API_KEY}
    depends_on:
      - redis
    networks:
      - searxng-net
    logging: &logging_defaults
      driver: "json-file"
      options: { max-size: "10m", max-file: "3" }

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      # Docker follows this symlink to store data in /opt/docker-data/redis
      - ./redis-data:/data
    networks:
      - searxng-net
    logging: *logging_defaults

networks:
  searxng-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.61.0.0/24"