# ================================
# SearXNG Settings
# ================================

general:
  instance_name: "My Private SearXNG"
  default_locale: "bn"

doi_resolvers:
  doi.org: "https://doi.org/"
  oadoi.org: "https://oadoi.org/"
default_doi_resolver: "doi.org"

server:
  secret_key: "CHANGE_ME_TO_A_VERY_STRONG_RANDOM_KEY"
  limiter: false

limiter:
  rates: "240 per 1 minute"

http:
  # API Key support
  api_keys:
    - "!!ENV SEARXNG_API_KEY"

valkey:
  url: "redis://redis:6379/0"

search:
  formats:
    - json
  request_timeout: 5.0

# ================================
# Engines
# ================================
# Use default engines, but only enable the safe ones
use_default_engines: true

engines:
  - name: google
    engine: google
    shortcut: gg
    categories: ['general']
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    categories: ['general']
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    categories: ['general', 'science']
    disabled: false
