# /elasticsearch-secure/docker-compose.yml
# COMPLETELY INSECURE ELASTICSEARCH DEPLOYMENT (FOR DEVELOPMENT ONLY)

services:
  elasticsearch:
    image: elasticsearch:8.15.1
    container_name: elastic_local_insecure
    restart: unless-stopped

    # Bind the HTTP port only to localhost.
    ports:
      - "127.0.0.1:9200:9200"

    volumes:
      - ./data:/usr/share/elasticsearch/data

    environment:
      # --- Cluster Setup ---
      - discovery.type=single-node

      # --- THIS IS THE KEY CHANGE ---
      # Explicitly disable all security features (password, TLS, etc.).
      - xpack.security.enabled=false

      # --- Performance Tuning ---
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

    healthcheck:
      # The check is now a simple, unauthenticated HTTP request.
      test: >
        [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health |
          grep -q '\"status\":\"green\|yellow\"'" ]
      interval: 20s
      timeout: 10s
      retries: 5

# NOTE: There is no 'secrets:' block in this file.