# /redis-secure/docker-compose.yml
# DEVELOPMENT-ONLY (INSECURE) CONFIGURATION

services:
  redis:
    # We can use the official redis image or bitnami, both work for this.
    # The official image is slightly more lightweight.
    image: redis:7-alpine
    container_name: redis_local_dev
    restart: unless-stopped

    # As a best practice, still bind to localhost to prevent accidental exposure.
    ports:
      - "127.0.0.1:6379:6379"

    volumes:
      # Map the persistent data directory. The internal path is different for the official image.
      - ./data:/data

    healthcheck:
      # The healthcheck is now a simple PING command.
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5