# --- Vector Retriever Configuration ---

# Number of top results to retrieve from each collection
top_k: 3

# A list of all collection names to be queried
collections:
  - "PassageDB"
  - "TopicDB"
  - "KeywordDB"

# The primary collection that contains the full passage content,
# used to retrieve the final documents based on passage_ids.
passage_collection: "PassageDB"