# config.yml
# Main configuration file for the Intelligent Crawler API

crawler:
  global_task_timeout: 4
  browser_page_timeout: 3

  target_elements:
    - "#left-content"
    - "#left"
  excluded_tags:
    - "script"
    - "style"
    - "noscript"
    - "header"
    - "footer"
    - "nav"
  excluded_selectors:
    - ".share-buttons"
    - ".print_btn"
    - ".social-media-icons"
    - ".noprint"
  verbose: true

search:
  num_results: 50
  timeout: 5.0

api:
  filter_domain: ".gov.bd"
  
  excluded_file_extensions:
    - ".pdf"
    - ".png"
    - ".jpg"
    - ".jpeg"
    - ".gif"
    - ".bmp"
    - ".svg"
    - ".webp"
    - ".docx"
    - ".doc"
    - ".xlsx"
    - ".xls"
    - ".pptx"
    - ".ppt"
    - ".zip"
    - ".rar"
    - ".tar.gz"
    - ".mp4"
    - ".mp3"
    - ".avi"
    - ".mov"