# -----------------------------------------------------------------
# Data Configuration for the ChromaDB Ingestion Script
#
# This file defines the source data, the target collection,
# and how to map the data columns.
# -----------------------------------------------------------------

# The name of the collection to create or use in ChromaDB
collection_name: "PassageDB"

# Relative or absolute path to the input CSV file
csv_file_path: "/home/vpa/Downloads/data/master_data_20250830.csv"

# --- Data Mapping ---

# The column in the CSV containing the document text to embed
content_column: "passage" 

# A list of columns from the CSV to store as metadata.
# Each of these columns must exist in the CSV file.
metadata_columns:
  - "category"
  - "passage_id"
  - "url"
  
# --- Ingestion Settings ---

# Number of documents to process and insert in a single batch
batch_size: 1